---
- name: Copy dockerfile
  ansible.builtin.copy:
    src: files/dockerfile
    dest: /tmp/Dockerfile
    mode: "0644"
  register: nodered_dockerfile_copy

- name: Create backup script
  become: true
  ansible.builtin.copy:
    src: "files/backup.sh"
    dest: "/tmp/backup.sh"
    mode: "0644"
  register: nodered_backup_script_copy

- name: Build Docker image
  become: true
  community.docker.docker_image:
    name: "{{ nodered_backup_image_name }}"
    tag: "{{ nodered_backup_image_tag }}"
    source: build
    push: false
    build:
      path: /tmp
    force_source: "{{ nodered_dockerfile_copy.changed or nodered_backup_script_copy.changed }}"
    state: present
  notify: "Restart {{ nodered_service_name }}"

- name: Create backup .env file
  become: true
  ansible.builtin.template:
    src: templates/docker-compose/backup-toolkit.env.j2
    dest: "{{ nodered_service_config_dir }}/backup-toolkit.env"
    group: "{{ nodered_service_user }}"
    owner: "{{ nodered_service_user }}"
    mode: "0400"
  notify: "Restart {{ nodered_service_name }}"

- name: Create backup systemd service file for {{ nodered_service_name }}
  become: true
  ansible.builtin.template:
    src: "templates/backup/backup.service.j2"
    dest: /etc/systemd/system/{{ nodered_service_name }}-backup.service
    owner: root
    group: root
    mode: "0644"
  register: nodered_backup_service

- name: Create backup systemd timer file for {{ nodered_service_name }}
  become: true
  ansible.builtin.template:
    src: "templates/backup/backup.timer.j2"
    dest: /etc/systemd/system/{{ nodered_service_name }}-backup.timer
    owner: root
    group: root
    mode: "0644"
  register: nodered_backup_timer

- name: Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
  when: nodered_backup_service.changed or nodered_backup_timer.changed

- name: Enable and start backup timer for {{ nodered_service_name }}
  become: true
  ansible.builtin.systemd:
    name: "{{ nodered_service_name }}-backup.timer"
    enabled: true
    state: started
