---
- name: Create service user {{ nodered_service_user }}
  become: true
  ansible.builtin.user:
    name: "{{ nodered_service_user }}"
    create_home: false
    comment: "{{ nodered_service_user }} user with no shell access"
    shell: /bin/false
  register: nodered_user_result

- name: Create config directory {{ nodered_service_config_dir }}
  become: true
  ansible.builtin.file:
    path: "{{ nodered_service_config_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ nodered_service_user }}"
    group: "{{ nodered_service_user }}"

- name: Create data directory {{ nodered_service_data_dir }}
  become: true
  ansible.builtin.file:
    path: "{{ nodered_service_data_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ nodered_service_user }}"
    group: "{{ nodered_service_user }}"

- name: Add users to docker group
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items:
    - root
    - noxious
    - "{{ nodered_service_user }}"
